name: Verify

on: 
  workflow_dispatch:

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 16]
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: verifier test
      working-directory: ./verifier
      run: |
        npm install
        npm test
      env:
        CI: true